build:
  environment:
    php:
      version: "7.4"
  nodes:
    coverage:
      services:
        maria-db2:
          image: docker.io/library/mariadb:10.5.9
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
          ports:
            - 3306
      tests:
        before:
          - cp .env.scrutinizer .env
        override:
          - command: composer phpunit-xml
            coverage:
              file: phpunit.coverage.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run
