language: php

php:
  - 7.4
  - 8.0

services:
  - mysql

cache:
  directories:
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE `test`;'
  - composer install --no-interaction

script:
  - composer phpcs-auto-check-project
  - composer phpunit
